[book]
authors = ["tramis"]
language = "zh"
# multilingual = false
discription = "wo cao ni ma"
src = "src"
title = "Learning Blogs"

[preprocessor.katex]
after = ["links"]

# [output.html]
# mathjax-support = true